services:
  app:
    build: ./app
    container_name: obs-app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EXTERNAL_API_URL: http://external-api:8081

      OTEL_SERVICE_NAME: observability-app
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: obs-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: obs-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  external-api:
    image: python:3.13-slim
    container_name: obs-external-api
    working_dir: /srv
    volumes:
      - ./external-api.py:/srv/external-api.py:ro
    command: ["python", "external-api.py"]

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: obs-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheusdata:/prometheus
    depends_on:
      - app
      - db
      - redis
      - external-api

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: obs-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanagerdata:/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    restart: unless-stopped


  grafana:
    image: grafana/grafana:12.1.0
    container_name: obs-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.20.0
    container_name: obs-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  loki:
    image: grafana/loki:3.5.0
    container_name: obs-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  alloy:
    image: grafana/alloy:latest
    container_name: obs-alloy
    ports:
      - "12345:12345"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./alloy:/etc/alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    depends_on:
      - loki


  locust:
    image: locustio/locust
    container_name: obs-locust
    ports:
      - "8089:8089"
    volumes:
      - ./loadtest:/mnt/locust
    command: -f /mnt/locust/locustfile.py

volumes:
  pgdata:
  prometheusdata:
  grafanadata:
  alertmanagerdata:
